# Generated by Django 3.2.8 on 2021-10-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('price', models.FloatField()),
                ('available_units', models.IntegerField(default='')),
                ('description', models.TextField(default='', max_length=500)),
                ('seller', models.TextField(max_length=100)),
                ('categories', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='base.category')),
                ('ratings', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.rating')),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reviews')),
            ],
        ),
    ]
