# Generated by Django 3.2.8 on 2021-10-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
