# Generated by Django 3.2.8 on 2021-10-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='delivery_address',
            field=models.CharField(default='Default address', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(default='User', max_length=100),
        ),
    ]
