# Generated by Django 3.2.8 on 2021-10-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20211030_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
